### ISSUE TITLE
CUADRO COMPARATIVO DE LAS CARACTERISTICAS DE LOS DIFERENTES TIPOS DE TEXTOS Y SU ESTRUCTURA

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-irvinjs22620075#1]
![Cuadr0 comparativo tipo de textos](https://user-images.githubusercontent.com/112287287/191655523-022e7417-5bc3-4e05-9337-7f179c355fc7.jpg)

**Comment by 11042002** [comment]
Tu calificación es de: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
